@DotNetWebApi_HostAddress = http://localhost:5089

GET {{DotNetWebApi_HostAddress}}/games
Accept: application/json

###
POST {{DotNetWebApi_HostAddress}}/games
Content-Type: application/json

{
  "title": "New Game",
  "genre": "Action",
  "price": 59.99,
  "releaseDate": "2024-01-01"
}

###
GET {{DotNetWebApi_HostAddress}}/games/1
Accept: application/json

###
PUT {{DotNetWebApi_HostAddress}}/games/1
Content-Type: application/json

{
  "title": "Updated Game",
  "genre": "Adventure",
  "price": 49.99,
  "releaseDate": "2024-02-01"
}

###
DELETE {{DotNetWebApi_HostAddress}}/games/1
